# Numpy - Library we will use for data Analysis

In [2]:
import numpy as np

# Creation of Numpy array

In [3]:
x = np.array([1,2,3,4,5])
print(x)
print(type(x)) # is is an ndarray

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Properties of numpy

In [5]:
# shape and size
print(x.size)   # total number of elements
print(x.shape)  # dimensions wise elements
print("dimenstions",x.ndim)     # number of dimensions

5
(5,)
dimenstions 1


In [7]:
x2d = np.array([[1,2,3],[4,5,6]])
print(x2d)

print(x2d.size)   # total number of elements
print(x2d.shape)  # dimensions wise elements
print("dimenstions",x2d.ndim)


[[1 2 3]
 [4 5 6]]
6
(2, 3)
dimenstions 2


# Shortcut to create an array full of random numbers

### random is a function specifiacally for arrays

In [9]:
x25 = np.random.randint(1,100,(5,5)) # 5 X 5 array with numbers ranging from 1 to 99
print(x25)

[[98 53 31 65 92]
 [90 67 60 29 32]
 [ 3 95 97  9 53]
 [ 5 35 13 91 41]
 [97 53 35 50 59]]


# 1D array using arrange

In [13]:
xseq1 = np.arange(1,101,4)
print("1D array")
print(xseq1)
print(xseq1.size)



print("1D array reshaped to 2d")
print(xseq1.reshape(5,5))


1D array
[ 1  5  9 13 17 21 25 29 33 37 41 45 49 53 57 61 65 69 73 77 81 85 89 93
 97]
25
1D array reshaped to 2d
[[ 1  5  9 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]
 [61 65 69 73 77]
 [81 85 89 93 97]]


## In linspace in 3rd argument we define how much elements we want it will generate that amoiunt of numbers with linear spacing

In [20]:
xseq2d = np.linspace(1,101,50)
print("1D array")
print(xseq2d)
print(xseq2d.size)



print("1D array reshaped to 2d")
print(xseq2d.reshape(10,5))

1D array
[  1.           3.04081633   5.08163265   7.12244898   9.16326531
  11.20408163  13.24489796  15.28571429  17.32653061  19.36734694
  21.40816327  23.44897959  25.48979592  27.53061224  29.57142857
  31.6122449   33.65306122  35.69387755  37.73469388  39.7755102
  41.81632653  43.85714286  45.89795918  47.93877551  49.97959184
  52.02040816  54.06122449  56.10204082  58.14285714  60.18367347
  62.2244898   64.26530612  66.30612245  68.34693878  70.3877551
  72.42857143  74.46938776  76.51020408  78.55102041  80.59183673
  82.63265306  84.67346939  86.71428571  88.75510204  90.79591837
  92.83673469  94.87755102  96.91836735  98.95918367 101.        ]
50
1D array reshaped to 2d
[[  1.           3.04081633   5.08163265   7.12244898   9.16326531]
 [ 11.20408163  13.24489796  15.28571429  17.32653061  19.36734694]
 [ 21.40816327  23.44897959  25.48979592  27.53061224  29.57142857]
 [ 31.6122449   33.65306122  35.69387755  37.73469388  39.7755102 ]
 [ 41.81632653  43.85714286  45.8

In [22]:
xseq2d = xseq2d.reshape(10,5)
print(xseq2d)

[[  1.           3.04081633   5.08163265   7.12244898   9.16326531]
 [ 11.20408163  13.24489796  15.28571429  17.32653061  19.36734694]
 [ 21.40816327  23.44897959  25.48979592  27.53061224  29.57142857]
 [ 31.6122449   33.65306122  35.69387755  37.73469388  39.7755102 ]
 [ 41.81632653  43.85714286  45.89795918  47.93877551  49.97959184]
 [ 52.02040816  54.06122449  56.10204082  58.14285714  60.18367347]
 [ 62.2244898   64.26530612  66.30612245  68.34693878  70.3877551 ]
 [ 72.42857143  74.46938776  76.51020408  78.55102041  80.59183673]
 [ 82.63265306  84.67346939  86.71428571  88.75510204  90.79591837]
 [ 92.83673469  94.87755102  96.91836735  98.95918367 101.        ]]


# Creating array full of a particular number using ones

In [24]:
# by deafualt it will take float 

one_arr = np.ones ((5,5), dtype = 'int')
one_arr


array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Next
- indexing and slicing
- boolean filter
- maths and stats
- methods

In [25]:
x25

array([[98, 53, 31, 65, 92],
       [90, 67, 60, 29, 32],
       [ 3, 95, 97,  9, 53],
       [ 5, 35, 13, 91, 41],
       [97, 53, 35, 50, 59]])

# if we want to extract 1st row amd last row

In [28]:
print(x25[0]) #first
print(x25[-1]) #last

[98 53 31 65 92]
[97 53 35 50 59]


# Extracting a particular element 

In [29]:
print(x25[0,1]) # same as print(x25[0][1])

53


# Extracting 1st column from ndarray

In [30]:
print(x25[:,0])     # first column

[53 67 95 35 53]


In [32]:
print(x25[:,-1])    # last column

[92 32 53 41 59]


# Extracting multiple columns

In [37]:
print(x25 [:,[0,1,2]])
# column 0 1 and 2

#same as above
print(x25[:, :3])




[[98 53 31]
 [90 67 60]
 [ 3 95 97]
 [ 5 35 13]
 [97 53 35]]
[[98 53 31]
 [90 67 60]
 [ 3 95 97]
 [ 5 35 13]
 [97 53 35]]


# Boolean Filter

In [38]:
x25

array([[98, 53, 31, 65, 92],
       [90, 67, 60, 29, 32],
       [ 3, 95, 97,  9, 53],
       [ 5, 35, 13, 91, 41],
       [97, 53, 35, 50, 59]])

In [41]:
for i in x25: # traverse in 2d form
    print (i)

[98 53 31 65 92]
[90 67 60 29 32]
[ 3 95 97  9 53]
[ 5 35 13 91 41]
[97 53 35 50 59]


In [43]:
for i in x25: # traverse in 1d form
    for j in i:     # i is a full row
        print(j)    # j is one element in i

98
53
31
65
92
90
67
60
29
32
3
95
97
9
53
5
35
13
91
41
97
53
35
50
59


# Normal Filtering

In [47]:
for i in x25: # traverse in 1d form
    for j in i: 
        if j<20:
            print(j)   

3
9
5
13


# Boolean Filtering

In [45]:
x25<=20         # new mask array will be created

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False,  True, False],
       [ True, False,  True, False, False],
       [False, False, False, False, False]])

In [56]:
x25[x25<=20]

array([ 3,  9,  5, 13])

In [49]:
x25[x25>50]

array([98, 53, 65, 92, 90, 67, 60, 95, 97, 53, 91, 97, 53, 59])

In [54]:
(x25 >20) & (x25<70)

array([[False,  True,  True,  True, False],
       [False,  True,  True,  True,  True],
       [False, False, False, False,  True],
       [False,  True, False, False,  True],
       [False,  True,  True,  True,  True]])

In [55]:
x25[(x25 >20) & (x25<70)]

array([53, 31, 65, 67, 60, 29, 32, 53, 35, 41, 53, 35, 50, 59])

## some fuctions of numpy are directly applicable to variables while some need to be applied like numpy.append in our case np.append

In [63]:
np.append(x25, np.array([[1,2,3,4,5]]),axis = 0)

array([[98, 53, 31, 65, 92],
       [90, 67, 60, 29, 32],
       [ 3, 95, 97,  9, 53],
       [ 5, 35, 13, 91, 41],
       [97, 53, 35, 50, 59],
       [ 1,  2,  3,  4,  5]])

In [64]:
x25

array([[98, 53, 31, 65, 92],
       [90, 67, 60, 29, 32],
       [ 3, 95, 97,  9, 53],
       [ 5, 35, 13, 91, 41],
       [97, 53, 35, 50, 59]])

# Arrays 2X3 amd 3X2

In [71]:
arr1 = np.array([[1,2,3],[4,5,6]])


In [74]:
arr2 = np.array([[1,2],[2,3],[3,4]])

## Now we will stack arr2 with arr1 -
- but both are of different shapes
- we will transpose arr2

In [75]:
arr2.T

array([[1, 2, 3],
       [2, 3, 4]])

In [78]:
print(np.hstack((arr1,arr2.T))) # horizontal stack

[[1 2 3 1 2 3]
 [4 5 6 2 3 4]]


In [79]:
print(np.vstack((arr1,arr2.T))) # vertical stack

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [2 3 4]]


In [4]:
x = np.random.randint(1,10, (3,3))
y = np.random.randint(1,10, (3,3))
print(x)
print(y)

[[7 3 4]
 [1 2 2]
 [3 9 4]]
[[9 3 9]
 [6 3 3]
 [9 5 7]]


# Numpy allows easy element wise operations like we have in matrices

In [11]:
print(x)
print(y)


[[7 3 4]
 [1 2 2]
 [3 9 4]]
[[9 3 9]
 [6 3 3]
 [9 5 7]]


In [5]:
print(x+y) #addition
print(x-y) #susbstraction
print(x/y) #divide
print(x%y) #element wise multipication
print(x*y) #element wise multiplication

[[16  6 13]
 [ 7  5  5]
 [12 14 11]]
[[-2  0 -5]
 [-5 -1 -1]
 [-6  4 -3]]
[[0.77777778 1.         0.44444444]
 [0.16666667 0.66666667 0.66666667]
 [0.33333333 1.8        0.57142857]]
[[7 0 4]
 [1 2 2]
 [3 4 4]]
[[63  9 36]
 [ 6  6  6]
 [27 45 28]]


In [7]:
print(x.dot(y))
print()

[[117  50 100]
 [ 39  19  29]
 [117  56  82]]



In [8]:
x.sum() # sum of all elements

35

In [12]:
x.sum(axis=0)   #row wise sum 0 means row 1 means column

array([11, 14, 10])

In [13]:
x.sum(axis=1)   #row wise sum 0 means row 1 means column

array([14,  5, 16])

In [15]:
print(x.mean())        # mean
print(x.mean(axis=0))  # row wise mean
print(x.mean(axis=1))  # column wise mean

3.888888888888889
[3.66666667 4.66666667 3.33333333]
[4.66666667 1.66666667 5.33333333]


In [16]:
print(x.max())      # max value
print(x.min())      # min value
print(x.argmax())   # index of max value
print(x.argmin())   # index of min value

9
1
7
3


In [19]:
print(np.median(x))
print(np.mean(x))

3.0
3.888888888888889


# Pandas library
- data read
- data load
- data analysis 
- data visualization
